# Generated by Django 5.2.16 on 2026-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Pain Relief', 'Pain Relief'), ('Antibiotic', 'Antibiotic'), ('Vitamin', 'Vitamin'), ('Allergy', 'Allergy'), ('Diabetes', 'Diabetes'), ('Heart', 'Heart'), ('Other', 'Other')], default='Other', max_length=50)),
                ('dosage', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('uses', models.TextField()),
                ('side_effects', models.TextField()),
                ('prescription_required', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
