# Generated by Django 5.2.16 on 2026-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAI', '0007_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expected_restock',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
