# Generated by Django 5.2.16 on 2026-07-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAI', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
