# Generated by Django 5.2.15 on 2026-08-21 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAI', '0011_agentauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='RECEIVED', max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Pain Relief', 'Pain Relief'), ('Fever & Cold', 'Fever & Cold'), ('Allergy', 'Allergy'), ('Digestive Health', 'Digestive Health'), ('Vitamins & Supplements', 'Vitamins & Supplements'), ('Diabetes Care', 'Diabetes Care'), ('Blood Pressure', 'Blood Pressure'), ('Skin Care', 'Skin Care'), ('First Aid', 'First Aid'), ('Respiratory', 'Respiratory'), ('Eye Care', 'Eye Care'), ('Oral Care', 'Oral Care'), ("Women's Health", "Women's Health"), ('General Health', 'General Health'), ('Antibiotic', 'Antibiotic'), ('Heart', 'Heart'), ('Other', 'Other')], default='General Health', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_APPROVAL', max_length=30)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='MediAI.inventory')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='MediAI.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='MediAI.pharmacy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
