# Generated by Django 5.2.15 on 2026-08-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAI', '0013_order_reservation_reservation_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Paid Online (Razorpay)'), ('PayOnPickup', 'Pay at Pharmacy on Pickup')], default='PayOnPickup', max_length=20),
        ),
    ]
