# Generated by Django 5.2.15 on 2026-08-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0016_alter_userprofile_pharmacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='package_size',
            field=models.CharField(blank=True, choices=[('Strip of 10', 'Strip of 10'), ('Strip of 15', 'Strip of 15'), ('Strip of 30', 'Strip of 30'), ('Bottle of 60', 'Bottle of 60'), ('Bottle of 100', 'Bottle of 100'), ('Bottle of 100 ml', 'Bottle of 100 ml'), ('Bottle of 200 ml', 'Bottle of 200 ml'), ('Tube of 20 g', 'Tube of 20 g'), ('Tube of 30 g', 'Tube of 30 g'), ('Sachet', 'Sachet'), ('Box of 1', 'Box of 1'), ('Vial / Ampoule', 'Vial / Ampoule'), ('Unit', 'Unit')], default='Strip of 15', help_text='Packaging SKU e.g. Strip of 15, Strip of 30, Bottle of 100', max_length=80),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku_code',
            field=models.CharField(blank=True, help_text='Unique SKU identifier e.g. DOLO650-S15', max_length=60, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('pharmacy', 'medicine', 'package_size')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['pharmacy', 'medicine'], name='MediAI_in_pharmac_0b199f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['medicine', 'quantity'], name='MediAI_in_medicin_c3d8b3_idx'),
        ),
    ]
