# Generated by Django 5.2.15 on 2026-08-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0017_alter_inventory_options_inventory_package_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='license_number',
            field=models.CharField(blank=True, help_text='Form 20/21 Drug License Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='verification_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Verification Pending'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='claimed_pharmacy',
            field=models.ForeignKey(blank=True, help_text='Pharmacy being claimed while verification is pending', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimants', to='medifind.pharmacy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Verification Pending'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
        migrations.CreateModel(
            name='PharmacyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_license_number', models.CharField(default='PENDING-DOCS', help_text='Form 20/21 Drug Retail License Number', max_length=100)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=30, null=True)),
                ('owner_proof', models.CharField(blank=True, help_text='Owner contact proof or license name', max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Verification Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_claims', to='medifind.pharmacy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pharmacy_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
