# Generated by Django 5.2.16 on 2026-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0018_pharmacy_license_number_pharmacy_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='api_auth_token',
            field=models.CharField(blank=True, help_text='API Secret Key or Bearer Token for POS integration', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='api_endpoint_url',
            field=models.URLField(blank=True, help_text='Direct POS/ERP API endpoint URL for real-time inventory lookup', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='api_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent real-time API inventory query', null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='api_sync_enabled',
            field=models.BooleanField(default=False, help_text='Enable real-time inventory checks via Pharmacy API'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='api_sync_status',
            field=models.CharField(blank=True, default='No API Configured', help_text='Current health/connectivity status of pharmacy API', max_length=100),
        ),
    ]
