# Generated by Django 5.2.15 on 2026-08-25 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0019_rename_mediai_in_pharmac_0b199f_idx_medifind_in_pharmac_0b199f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('document_type', models.CharField(default='prescription', max_length=50)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('prescription_date', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('confirmed_medicines', models.JSONField(default=list)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('requires_confirmation', models.BooleanField(default=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]

