# Generated by Django 5.2.15 on 2026-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0020_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prescription_image',
            field=models.ImageField(blank=True, help_text='Uploaded doctor prescription file for prescription-required medicines', null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prescription_uploaded',
            field=models.BooleanField(default=False, help_text='True if a valid doctor prescription has been uploaded for this reservation'),
        ),
    ]
