# Generated by Django 5.2.15 on 2026-08-25 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0021_rename_mediai_in_pharmac_0b199f_idx_medifind_in_pharmac_0b199f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDemandSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('reservations_count', models.PositiveIntegerField(default=0)),
                ('searches_count', models.PositiveIntegerField(default=0)),
                ('stock_at_end', models.PositiveIntegerField(default=0)),
                ('was_out_of_stock', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True)),
                ('horizon_days', models.PositiveIntegerField(default=7)),
                ('predicted_demand', models.FloatField(default=0.0)),
                ('lower_bound', models.FloatField(default=0.0)),
                ('upper_bound', models.FloatField(default=0.0)),
                ('days_of_cover', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=20)),
                ('trend', models.CharField(choices=[('STABLE', 'Stable Demand'), ('INCREASING', 'Increasing Demand'), ('DECREASING', 'Decreasing Demand'), ('SPIKE', 'Unusual Demand Spike')], default='STABLE', max_length=20)),
                ('reorder_recommended', models.BooleanField(default=False)),
                ('suggested_reorder_qty', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('safety_stock', models.PositiveIntegerField(default=0)),
                ('raw_data_points', models.PositiveIntegerField(default=0)),
                ('is_cold_start', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('training_data_start', models.DateField(blank=True, null=True)),
                ('training_data_end', models.DateField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('wape', models.FloatField(blank=True, help_text='Weighted Absolute Percentage Error', null=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailydemandsnapshot',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_snapshots', to='medifind.medicine'),
        ),
        migrations.AddField(
            model_name='dailydemandsnapshot',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_snapshots', to='medifind.pharmacy'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='medifind.inventory'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='medifind.medicine'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='medifind.pharmacy'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medifind.forecastmodelversion'),
        ),
        migrations.AddIndex(
            model_name='dailydemandsnapshot',
            index=models.Index(fields=['pharmacy', 'medicine', 'date'], name='medifind_da_pharmac_97bd51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydemandsnapshot',
            unique_together={('pharmacy', 'medicine', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='demandforecast',
            unique_together={('pharmacy', 'medicine', 'forecast_date', 'horizon_days')},
        ),
    ]
