# Generated by Django 5.2.15 on 2026-08-25 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0022_dailydemandsnapshot_demandforecast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('INVENTORY_MISMATCH', 'Inventory Movement Mismatch'), ('RAPID_STOCK_MANIPULATION', 'Rapid Stock Toggling'), ('CANCELLATION_SPIKE', 'Cancellation Rate Spike'), ('PRICE_ANOMALY', 'Unusual Price Spike'), ('SEARCH_SURGE', 'Search Volume Surge'), ('DUPLICATE_PHARMACY', 'Potential Duplicate Pharmacy'), ('DUPLICATE_MEDICINE', 'Potential Duplicate Medicine')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Severity')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('REVIEWING', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('ESCALATED', 'Escalated')], db_index=True, default='DETECTED', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('evidence_json', models.JSONField(default=dict)),
                ('risk_score', models.FloatField(default=50.0)),
                ('review_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='operationalanomalyalert',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='medifind.inventory'),
        ),
        migrations.AddField(
            model_name='operationalanomalyalert',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='medifind.medicine'),
        ),
        migrations.AddField(
            model_name='operationalanomalyalert',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='medifind.pharmacy'),
        ),
        migrations.AddField(
            model_name='operationalanomalyalert',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anomaly_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalanomalyalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='operationalanomalyalert',
            index=models.Index(fields=['severity', 'status'], name='medifind_op_severit_e60e43_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalanomalyalert',
            index=models.Index(fields=['pharmacy', 'created_at'], name='medifind_op_pharmac_9858ef_idx'),
        ),
    ]
