# Generated by Django 5.2.15 on 2026-08-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0023_operationalanomalyalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMPharmacyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, default='Pharmacy', max_length=255)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('district', models.CharField(blank=True, default='', max_length=150)),
                ('postcode', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('opening_hours', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='OpenStreetMap', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='osmpharmacylocation',
            index=models.Index(fields=['latitude', 'longitude'], name='medifind_os_latitud_e4c64c_idx'),
        ),
        migrations.AddIndex(
            model_name='osmpharmacylocation',
            index=models.Index(fields=['city'], name='medifind_os_city_37570a_idx'),
        ),
    ]
