# Generated by Django 5.2.16 on 2026-08-27 10:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifind', '0024_osmpharmacylocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('FINALIZED', 'Finalized Revenue'), ('VOIDED', 'Voided / Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='net_pharmacy_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='MediAI platform commission percentage (default: 3.00%)', max_digits=5),
        ),
    ]
